# Force all Gradle workers to use your modified Homebrew Java 25 truststore
systemProp.javax.net.ssl.trustStore=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/lib/security/cacerts
systemProp.javax.net.ssl.trustStorePassword=
org.gradle.java.installations.paths=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home

org.gradle.jvmargs=--enable-native-access=ALL-UNNAMED
